const KEY="amlak_pwa_v1";let db=JSON.parse(localStorage.getItem(KEY)||'{"clients":[],"properties":[],"visits":[],"followups":[]}');let deferredPrompt=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem(KEY,JSON.stringify(db));renderAll()}
function uid(p){return p+"-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,6)}
function today(){return new Date().toISOString().slice(0,10)}
function faDate(d){if(!d)return "";return new Intl.DateTimeFormat("fa-IR",{year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(d+"T00:00:00"))}
function toast(t){let x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1800)}
function nav(id){$$(".screen").forEach(x=>x.classList.toggle("active",x.id===id));$$(".bottom-nav button[data-nav]").forEach(x=>x.classList.toggle("active",x.dataset.nav===id));window.scrollTo(0,0)}
function newVisit(){nav("visit");$("#vFollowDate").value=today();$("#vFollowTime").value="17:00";$("#vAction").value="تماس با مشتری";$("#vNote").focus()}
document.addEventListener("click",e=>{let n=e.target.closest("[data-nav]");if(n)nav(n.dataset.nav);let a=e.target.closest('[data-action="new-visit"]');if(a)newVisit()});
$("#visitForm").addEventListener("submit",e=>{e.preventDefault();let client=$("#vClient").value.trim(),prop=$("#vProperty").value.trim();if(!client||!prop)return toast("نام مشتری و ملک را وارد کنید");
let c=db.clients.find(x=>x.name===client)||{id:uid("C"),name:client,phone:"",need:"خرید",budget:"",area:"",status:"جدید",created:today()};if(!db.clients.some(x=>x.id===c.id))db.clients.push(c);
let p=db.properties.find(x=>x.code===prop||x.address===prop)||{id:uid("P"),code:prop,address:prop,type:"آپارتمان",price:"",area:"",status:"فعال",owner:"",phone:"",created:today()};if(!db.properties.some(x=>x.id===p.id))db.properties.push(p);
let visit={id:uid("V"),date:today(),time:new Date().toLocaleTimeString("fa-IR",{hour:"2-digit",minute:"2-digit"}),clientId:c.id,client:c.name,propertyId:p.id,property:p.address||p.code,result:$("#vResult").value,price:$("#vPrice").value,action:$("#vAction").value,followDate:$("#vFollowDate").value,followTime:$("#vFollowTime").value,note:$("#vNote").value};
db.visits.unshift(visit);if(visit.followDate&&visit.action)db.followups.unshift({id:uid("F"),date:today(),due:visit.followDate,time:visit.followTime,type:"پیگیری بازدید",clientId:c.id,client:c.name,propertyId:p.id,property:p.address||p.code,subject:visit.action,action:visit.action,status:"انجام نشده",result:"",note:visit.note});save();toast("بازدید ثبت شد ✓");e.target.reset();setTimeout(()=>nav("home"),250)})
function renderAll(){renderHome();renderLists();renderClients();renderProperties();renderFollowups()}
function renderHome(){let open=db.followups.filter(x=>x.status!=="انجام شد");let t=open.filter(x=>x.due===today()).length,l=open.filter(x=>x.due<today()).length;$("#statToday").textContent=t;$("#statLate").textContent=l;$("#statClients").textContent=db.clients.length;$("#statProps").textContent=db.properties.length;$("#todayText").textContent=new Intl.DateTimeFormat("fa-IR",{weekday:"long",day:"numeric",month:"long"}).format(new Date());
let arr=open.sort((a,b)=>a.due.localeCompare(b.due)).slice(0,5);$("#homeFollowups").innerHTML=arr.length?arr.map(cardFollow).join(""):`<div class="card muted">فعلاً پیگیری ثبت‌شده‌ای ندارید.</div>`}
function renderLists(){$("#clientList").innerHTML=db.clients.map(x=>`<option value="${esc(x.name)}">`).join("");$("#propertyList").innerHTML=db.properties.map(x=>`<option value="${esc(x.code||x.address)}">`).join("")}
function renderClients(){let q=($("#clientSearch")?.value||"").trim().toLowerCase();let a=db.clients.filter(x=>(x.name+" "+x.phone+" "+x.area).toLowerCase().includes(q));$("#clientCards").innerHTML=a.length?a.map(x=>`<div class="card"><div class="card-top"><div><div class="card-title">${esc(x.name)}</div><div class="muted">${esc(x.phone||"بدون شماره")} · ${esc(x.area||"منطقه ثبت نشده")}</div></div><span class="badge">${esc(x.status||"جدید")}</span></div><div class="card-actions"><button class="outline" onclick="callPhone('${esc(x.phone||"")}')">📞 تماس</button><button class="outline" onclick="newVisitForClient('${esc(x.name)}')">＋ بازدید</button></div></div>`).join(""):`<div class="card muted">مشتری پیدا نشد.</div>`}
function renderProperties(){let q=($("#propertySearch")?.value||"").trim().toLowerCase();let a=db.properties.filter(x=>(x.code+" "+x.address+" "+x.area+" "+x.price+" "+x.type).toLowerCase().includes(q));$("#propertyCards").innerHTML=a.length?a.map(x=>`<div class="card"><div class="card-top"><div><div class="card-title">${esc(x.code||"ملک")}</div><div class="muted">${esc(x.type||"")} · ${esc(x.area||"")} · ${esc(x.address||"")}</div></div><span class="badge">${esc(x.status||"فعال")}</span></div><div class="muted" style="margin-top:7px">قیمت: ${esc(x.price||"ثبت نشده")} · مالک: ${esc(x.owner||"ثبت نشده")}</div></div>`).join(""):`<div class="card muted">ملکی پیدا نشد.</div>`}
function renderFollowups(filter="all"){let a=db.followups.filter(x=>x.status!=="انجام شد");if(filter==="today")a=a.filter(x=>x.due===today());if(filter==="late")a=a.filter(x=>x.due<today());if(filter==="open")a=a.filter(x=>x.status==="انجام نشده");a.sort((x,y)=>x.due.localeCompare(y.due));$("#followCards").innerHTML=a.length?a.map(cardFollow).join(""):`<div class="card muted">موردی وجود ندارد.</div>`}
function cardFollow(x){let late=x.due<today();return `<div class="card"><div class="card-top"><div><div class="card-title">${esc(x.subject||x.action||"پیگیری")}</div><div class="muted">${esc(x.client||"")} · ${esc(x.property||"")}</div></div><span class="badge ${late?"red":x.due===today()?"yellow":""}">${late?"عقب‌افتاده":x.due===today()?"امروز":faDate(x.due)}</span></div><div class="muted" style="margin-top:7px">${x.time?esc(x.time):""} ${x.note?" · "+esc(x.note):""}</div><div class="card-actions"><button class="outline" onclick="doneFollow('${x.id}')">✓ انجام شد</button>${clientPhone(x.clientId)?`<button class="outline" onclick="callPhone('${esc(clientPhone(x.clientId))}')">📞 تماس</button>`:""}</div></div>`}
function clientPhone(id){return (db.clients.find(x=>x.id===id)||{}).phone||""}
function doneFollow(id){let x=db.followups.find(x=>x.id===id);if(x){x.status="انجام شد";save();toast("پیگیری انجام شد ✓")}}
function callPhone(p){if(p)location.href="tel:"+p;else toast("شماره‌ای ثبت نشده است")}
function newVisitForClient(n){newVisit();$("#vClient").value=n}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
$("#clientSearch").addEventListener("input",renderClients);$("#propertySearch").addEventListener("input",renderProperties);
$("#addClient").addEventListener("click",()=>openModal("ثبت مشتری",`<label>نام<input id="mName"></label><label>شماره تماس<input id="mPhone" inputmode="tel"></label><label>نیاز<select id="mNeed"><option>خرید</option><option>رهن</option><option>اجاره</option></select></label><label>بودجه<input id="mBudget"></label><label>منطقه مورد نظر<input id="mArea"></label><button class="primary submit" onclick="saveClient()">ثبت</button>`));
$("#addProperty").addEventListener("click",()=>openModal("ثبت ملک",`<label>کد ملک<input id="pCode"></label><label>آدرس/محدوده<input id="pAddress"></label><label>نوع ملک<select id="pType"><option>آپارتمان</option><option>خانه</option><option>ویلایی</option><option>زمین</option><option>مغازه</option><option>اداری</option></select></label><label>متراژ<input id="pArea" inputmode="numeric"></label><label>قیمت<input id="pPrice"></label><label>نام مالک<input id="pOwner"></label><label>شماره مالک<input id="pPhone" inputmode="tel"></label><button class="primary submit" onclick="saveProperty()">ثبت</button>`));
function openModal(t,b){$("#modalTitle").textContent=t;$("#modalBody").innerHTML=b;$("#modal").classList.remove("hidden")}$("#closeModal").onclick=()=>$("#modal").classList.add("hidden");
function saveClient(){let x={id:uid("C"),name:$("#mName").value.trim(),phone:$("#mPhone").value.trim(),need:$("#mNeed").value,budget:$("#mBudget").value,area:$("#mArea").value,status:"جدید",created:today()};if(!x.name)return;db.clients.push(x);save();$("#modal").classList.add("hidden");toast("مشتری ثبت شد")}
function saveProperty(){let x={id:uid("P"),code:$("#pCode").value.trim(),address:$("#pAddress").value.trim(),type:$("#pType").value,area:$("#pArea").value,price:$("#pPrice").value,owner:$("#pOwner").value,phone:$("#pPhone").value,status:"فعال",created:today()};db.properties.push(x);save();$("#modal").classList.add("hidden");toast("ملک ثبت شد")}
$$(".chip").forEach(x=>x.addEventListener("click",()=>{$$(".chip").forEach(y=>y.classList.remove("active"));x.classList.add("active");renderFollowups(x.dataset.filter)}));
let rec;if("webkitSpeechRecognition"in window||"SpeechRecognition"in window){let SR=window.SpeechRecognition||window.webkitSpeechRecognition;rec=new SR();rec.lang="fa-IR";rec.interimResults=false;rec.onresult=e=>{$("#vNote").value+=(($("#vNote").value?" ":"")+e.results[0][0].transcript);toast("متن صوتی ثبت شد")};rec.onerror=()=>toast("ثبت صوتی در این مرورگر فعال نشد")}$("#voiceBtn").onclick=()=>rec?rec.start():toast("مرورگر شما از تبدیل گفتار پشتیبانی نمی‌کند");
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("#installBtn").classList.remove("hidden")});$("#installBtn").onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null}};
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));
renderAll();
